name: pay_net_api
description: A package to handle network communication.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.24.1
  very_good_analysis: ^4.0.0+1
dependencies:
  dio: ^5.1.1
  equatable: ^2.0.5
