name: bicycle_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  app_repo:
    path: packages/app_repo
  bloc: ^8.1.1
  # camera: ^0.10.5+5
  carousel_slider: ^4.2.1
  
  country_pickers: ^3.0.1
  dio: ^5.3.3
  easy_stepper: ^0.8.2
  equatable: ^2.0.5
  file_picker: ^6.1.1
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_image_compress: ^2.1.0
  flutter_google_places_sdk: ^0.3.7
  flutter_credit_card: ^3.0.1
  slide_to_act: ^2.0.2
  flutter_polyline_points_plus: ^3.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.8
  font_awesome_flutter: ^10.5.0
  geolocator: ^9.0.2
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  google_geocoding_api: ^1.4.1
 
  google_maps_flutter_android: ^2.6.2
  google_static_maps_controller: ^1.0.0
  image_picker: ^0.8.7+4
  intl: ^0.19.0
  lorem_ipsum: ^0.0.3
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  
  url_launcher: ^6.1.14
  uuid: ^4.0.0
  geocoding: ^3.0.0
  torch_light: ^1.0.0

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/isrgrootx1.pem
  
