part of 'loan.dart';

Loan _$LoanFromJson(Map<String, dynamic> json) => Loan(
      id: int.tryParse(json['id'].toString()) ?? 0,
      totalOustanding: json['total_outstanding_derived'] as String? ?? '',
      yearLength: json['yearLengthInDays'] as String? ?? '',
      totalInterest: json['total_interest_repaid'] as String? ?? '',
      title: json['title'] as String? ?? '',
      currencyDecimals:
          double.tryParse(json['currencyDecimals'].toString()) ?? 0,
      mobileNumber: json['mobileNumber'] as String? ?? '',
      principalAmountProposed:
          double.tryParse(json['principal_amount_proposed'].toString()) ?? 0,
      feeChargesRepaid: json['fee_charges_repaid_derived'] as String? ?? '',
      repaymentAmount: json['repayment_amount'] as String? ?? '',
      gender: json['gender'] as String? ?? '',
      status: json['status'] as String? ?? '',
      writtenoffonDate: json['writtenoffon_date'] as String? ?? '',
      chargesWrittenoff:
          json['fee_charges_writtenoff_derived'] as String? ?? '',
      approvedonDate: json['approvedon_date'] as String? ?? '',
      repayEvery: json['repay_every'] as String? ?? '',
      lastName: json['lastName'] as String? ?? '',
      financeCost: double.tryParse(json['finance_cost'].toString()) ?? 0,
      firstName: json['firstName'] as String? ?? '',
      loanStatus: json['loan_status'] as String? ?? '',
      appUserId: json['app_user_id'] as String? ?? '',
      disbursedonDate: json['disbursedon_date'] as String? ?? '',
      penaltyCharges: json['penalty_charges_repaid_derived'] as String? ?? '',
      totalCostofloan:
          json['total_expected_costofloan_derived'] as String? ?? '',
      interestMethod: json['interest_method'] as String? ?? '',
      name: json['name'] as String? ?? '',
      momoProvider: json['momoProvider'] as String? ?? '',
      penaltyChargesoutstanding:
          json['penalty_charges_outstanding_derived'] as String? ?? '',
      companyRegistrationDate: json['companyRegistrationDate'] as String? ?? '',
      interestCharged: json['interest_charged_derived'] as String? ?? '',
      loanType: json['productType'] as String? ?? '',
      interest: double.tryParse(json['interest'].toString()) ?? 0,
    );

Map<String, dynamic> _$LoanToJson(Loan instance) => <String, dynamic>{
      'id': instance.id,
      'total_outstanding_derived': instance.totalOustanding,
      'yearLengthInDays': instance.yearLength,
      'total_interest_repaid': instance.totalInterest,
      'title': instance.title,
      'currencyDecimals': instance.currencyDecimals,
      'mobileNumber': instance.mobileNumber,
      'principal_amount_proposed': instance.principalAmountProposed,
      'fee_charges_repaid_derived': instance.feeChargesRepaid,
      'approvedon_date': instance.approvedonDate,
      'repay_every': instance.repayEvery,
      'lastName': instance.lastName,
      'finance_cost': instance.financeCost,
      'firstName': instance.firstName,
      'loan_status': instance.loanStatus,
      'app_user_id': instance.appUserId,
      'disbursedon_date': instance.disbursedonDate,
      'penalty_charges_repaid_derived': instance.penaltyCharges,
      'total_expected_costofloan_derived': instance.totalCostofloan,
      'interest_method': instance.interestMethod,
      'name': instance.name,
      'momoProvider': instance.momoProvider,
      'interest_charged_derived': instance.interestCharged,
      'productType': instance.loanType,
      'companyRegistrationDate': instance.companyRegistrationDate,
      'interest': instance.interest,
    };

Map<String, dynamic> _$LoanToMap(Map<String, dynamic> json) =>
    <String, dynamic>{
      'id': int.tryParse(json['id'].toString()) ?? 0,
      'total_outstanding_derived': json['total_outstanding_derived'],
      'yearLengthInDays': json['yearLengthInDays'],
      'total_interest_repaid': json['total_interest_repaid'],
      'title': json['title'],
      'currencyDecimals': json['currencyDecimals'],
      'mobileNumber': json['mobileNumber'],
      'principal_amount_proposed': json['principal_amount_proposed'],
      'fee_charges_repaid_derived': json['fee_charges_repaid_derived'],
      'approvedon_date': json['approvedon_date'],
      'repay_every': json['repay_every'],
      'lastName': json['lastName'],
      'finance_cost': json['finance_cost'],
      'firstName': json['firstName'],
      'loan_status': json['loan_status'],
      'app_user_id': json['app_user_id'],
      'disbursedon_date': json['disbursedon_date'],
      'penalty_charges_repaid_derived': json['penalty_charges_repaid_derived'],
      'total_expected_costofloan_derived':
          json['total_expected_costofloan_derived'],
      'interest_method': json['interest_method'],
      'name': json['name'],
      'momoProvider': json['momoProvider'],
      'interest_charged_derived': json['interest_charged_derived'],
      'productType': json['productType'],
      'companyRegistrationDate': json['companyRegistrationDate'],
      'interest': json['interest'],
    };
